site_name: ar2pi
site_url: https://docs.ar2pi.net
site_author: Arthur Picerna
site_description: Arthur Picerna (ar2pi)

repo_url: https://github.com/ar2pi/ar2pi/
edit_uri: edit/main/docs/
remote_branch: main

nav:
  - About: index.md
  - Go: go.md
  - Python: python.md
  - Bash: bash.md
  - Git: git.md
  - Networking: networking.md
  - Prometheus Video Renderer: prometheus-video-renderer.md
  - Linux (Debian): linux-debian.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
