site_name: ar2pi
site_url: https://docs.ar2pi.net
repo_url: https://github.com/ar2pi/ar2pi/
edit_uri: edit/main/docs/
remote_branch: main

nav:
  - About: index.md
  - Python: python.md
  - Linux: linux.md
  - Network: network.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
