site_name: ar2pi
site_url: https://docs.ar2pi.net
site_author: Arthur Picerna
site_description: Arthur Picerna (ar2pi)

repo_url: https://github.com/ar2pi/ar2pi/
edit_uri: edit/main/docs/
remote_branch: main

nav:
  - About:
    - index.md
  - Cheatsheets:
    - python.md
    - go.md
    - shell.md
    - vim.md
    - git.md
    - networking.md
    - kubernetes.md
    - linux-debian.md
  - Labs:
    - labs/prometheus-video-renderer.md
  - poems.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
