site_name: ar2pi
site_url: https://docs.ar2pi.net
site_author: Arthur Picerna
site_description: Arthur Picerna (ar2pi)

repo_url: https://github.com/ar2pi/ar2pi/
edit_uri: edit/main/docs/
remote_branch: main

nav:
  - About:
    - index.md
  - Cheatsheets:
    - Go: go.md
    - Python: python.md
    - Shell: shell.md
    - Vim: vim.md
    - Git: git.md
    - Networking: networking.md
    - Kubernetes: kubernetes.md
    - Linux (Debian): linux-debian.md
  - Lab:
    - Prometheus Video Renderer: lab/prometheus-video-renderer.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
