#!/usr/bin/env bash

set -eu

source $(dirname ${BASH_SOURCE[0]})/utils/all.sh

exit_if_not_main_branch

out "Running post-merge hook"

out "Updating submodules"
git submodule update --remote --checkout
git submodule status

exit 0
