#!/usr/bin/env bash

set -eu

source $(dirname ${BASH_SOURCE[0]})/utils/all.sh

watch_files="docs/ mkdocs.yml"

exit_if_not_main_branch
exit_if_ci

out "Running pre-push hook"

if [[ $(git diff --name-status $current_branch "origin/$current_branch" -- $watch_files) ]]; then
    out warn "Changes to [$watch_files], consider running 'make publish'"
else
    out "No changes to [$watch_files], continue"
fi

exit 0
