#!/bin/bash

set -eu

NOCOLOR="\033[0m"
PINK="\033[0;35m"
current_branch=$(git branch --show-current)
watch_files="docs/ mkdocs.yml"

echo "Running pre-push hook:"

if [[ $(git diff --name-status $current_branch "origin/$current_branch" -- $watch_files) ]]; then
    echo -e "${PINK}Changes to $watch_files, deploying"
    make deploy
else
    echo -e "${PINK}No changes to $watch_files, continue"
fi

exit 0
